### ISSUE TITLE
Overcloud Provider added to Default Zone

### ISSUE THREAD

**Issue by kjw3** [jritenour/cf-ansible-conf#2]
When examining what was installed after running the OSP-full, I saw an OSP overcloud provider added. However, info wasn't being pulled in correctly.

After examining the configuration, I noticed that the provider was placed in the default zone instead of the openstack zone.

**Comment by jritenour** [comment]
Resolved - finally figured out the syntax for specifying the zone for a new provider via the API - http://manageiq.org/docs/reference/euwe/api/reference/providers.
